config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    post '/users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  get "contents/about" => "contents#about"

  root to: 'contents#index'

  resources :diaries
  resources :profiles, except: [:index, :destroy]

  resources :contents, except: [:destroy] do
    resources :descriptions, except: [:index, :show]
    resources :sentences, except: [:index, :show]
    resources :contents_histories, only: [:show]
    collection do
      get 'search'
    end
  end
end

app/models/content.rb
class Content < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :part

  with_options presence: true do
    validates :part_id, numericality: { other_than: 0, message: 'を選択してください' }, uniqueness: { scope: [:word] }
    validates :word, format: { with: /\A[a-z0-9]+\z/ }
  end

  belongs_to :user
  has_many :descriptions
  has_many :contents_histories

  def self.search(search)
    if search != ''
      Content.where('word LIKE(?)', "%#{search}%")
    else
      Content.all
    end
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :specified_content, only: [:show, :edit, :update]

  def index
    @contents = Content.all
    @content_post_ranking = User.order('content_count desc').limit(3)
    @description_post_ranking = User.order('description_count desc').limit(3)
    @sentence_post_ranking = User.order('sentence_count desc').limit(3)
    @diary_post_ranking = User.order('diary_count desc').limit(3)
  end

  def new
    @content = Content.new
  end

  def create
    @content = Content.new(content_params)
    if @content.save
      make_new_history
      make_count
      redirect_to content_path(@content.id),
      notice: '単語の追加に成功しました'
    else
      render :new
    end
  end

  def show
    @descriptions = Description.where(content_id: params[:id]).order('updated_at desc')
    @sentences = Sentence.where(content_id: params[:id]).order('updated_at desc')
    @contents_histories = ContentsHistory.where(content_id: params[:id]).order('updated_at desc').limit(3)
  end

  def edit
  end

  def update
    if @content.update(content_params)
      make_new_history
      redirect_to content_path(@content.id), notice: '単語の更新に成功しました'
    else
      render :edit
    end
  end

  def search
    @contents = Content.search(params[:keyword])
  end

  def about
    
  end

  private

  def content_params
    params.require(:content).permit(:part_id, :word).merge(user_id: current_user.id)
  end

  def specified_content
    @content = Content.find(params[:id])
  end

  def make_new_history
    new_history = @content.contents_histories.new
    new_history.user_id = current_user.id
    new_history.word = @content.word
    new_history.save
  end

  def make_count
    sum = current_user.content_count.to_i + 1
    current_user.update_column(:content_count, sum)
  end
end

app/helpers/contents_helper.rb
module ContentsHelper
  def content_lists(contents)
    html = ''
    contents.each do |content|
      html += render(partial: 'content', locals: { content: content })
    end
    raw(html)
  end
end

app/views/contents/_content.html.erb
<div class="description">
  <div>
    <b class="break-all"><%= content.word%></b>
    <br><%= content.part.name %>
  </div>
 
  <div>
    <%= content.created_at.strftime("%Y-%m-%d %H:%M") %>
  </div>

  <div class="description-bottom">
    <div>
      <%= link_to "詳細", content_path(content.id)%>
    </div>
  </div>
</div>

app/views/contents/_search_result.html.erb
<div class="one-result">
  <div>
    <b><%= contents.word%></b>
    <%= contents.part.name %>
  </div>
 
  <div>
    <%= contents.created_at %>
  </div>

  <div>
    <%= link_to "#{contents.word}を見る", content_path(contents.id) %>
  </div>
</div>

<%# CSS作成段階でスペースを削除すること %>
　
<%# //CSS作成段階でスペースを削除すること %>

app/views/contents/about.html.erb
<%= render "shared/header"%>

<div class="about-main">
  <div>
    <h1>
      WordStockについて
    </h1>
    <div>
      <div>
        WordStockは、英語学習者がより能動的に学習を進められる様に作成されたアプリケーションです。
      </div>
      <div>
        白紙の辞書に、単語を追加していき、意味を追加していき、例文を追加していく...そんなイメージです。
      </div>
      <div>
        他のユーザーたちと共に、自分のクリエイティビティを活かして、１冊の辞書を作り上げていきましょう！
      </div>
    </div>
  </div>
  
  <div class="useful-function">
    <h2>
      使える機能
    </h2>
    <div>
      ・単語の追加
    </div>
    <div>
      ・意味の追加
    </div>
    <div>
      ・例文の追加
    </div>
    <div>
      ・日記の投稿
    </div>
    <div>
      ・単語検索...etc
    </div>
  </div>

  <div class="about-english-learning">
    <h2>
      語学学習のキホン
    </h2>
    <div>
      語学学習において、インプットはもちろん大切ですが、使える能力を養うためにはアウトプットが必須項目です。
    </div>
    <div>
      アウトプットのコツ、それは
    </div>
    <div class="learning-points">
      <div class="learning-point">
        間違いを恐れないこと。
      </div>
      <div class="learning-point">
        そして、間違いを咎めないこと。
      </div>
    </div>
    <div>
      自ら間違えに気がつき、気がついた間違えを修正するまでが学習です。
    </div>
    <div>
      それが成長につながります。
    </div>
    <div>
      一緒に辞書を作り上げていきましょう！
    </div>
    <div class="get-started">
      <%= link_to "Let's get started!", root_path %>
    </div>
  </div>
</div>

<%= render "shared/footer"%>

app/views/contents/edit.html.erb
<%= render "shared/header" %>

<%= form_with model: @content, url: content_path, method: :patch, local: true do |f| %>

  <div class="new-show-content-main">
    <h2>
      <%= "#{@content.word}を編集" %>
    </h2>

    <div class="error-messages">
      <%= render 'shared/error_messages', model: f.object %>
    </div>

    <div class="font-size-twenty-five">
      <%# 品詞 %>
      <div>
        品詞
        <span class="indispensable">必須</span>
      </div>
      <%= f.collection_select(:part_id, Part.all, :id, :name, {}, {class:"select-box", id:"content-part"}) %>

      <%# 単語 %>
      <div>
        単語
        <span class="indispensable">必須</span>
      </div>
      <div>
        <%= f.text_field :word, class:"word-input", id:"word_id"%>
      </div>

      <div class="caution">
        ※固有名詞の追加は禁止です。
      </div>

      <%# 送信ボタン %>
      <div>
        <%= f.submit "更新する", class:"edit-btn" %>
      </div>
    </div>
  </div>

<% end %>

<%= render "shared/footer" %>

app/views/contents/index.html.erb
<%= render "shared/header" %>

  <div class="ok-flash">
    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>
  </div>

<div class="about-wordstock">
  <%= link_to "WordStockとは?", contents_about_path %>
</div>

<div class="main">
  <div class="left-content">
    <div class="contents">
      <%# 単語一覧 %>
      <div>
        <h2>
          単語一覧
        </h2>
        <% if user_signed_in? %>
          <div class="position-center">
            <%= link_to '単語追加', new_content_path, class:"new-btn" %>
          </div>
        <% end %>
        <div class="contents-group">
          <%= content_lists(@contents) %>
        </div>
      </div>
    </div>
  </div>


  <div class="right-content">
    <div class="ranking-group">
      <h2>
        ランキング
      </h2>

      <h3 class="contents-ranking">単語投稿回数</h3>
      <% @content_post_ranking.each.with_index(1) do |content, i| %>
        <div class="rank">
          第
          <%= i %>
          位
          <%= link_to "#{content.nickname}さん", profile_path(content.id), class: "ranking-nickname" %> <%= "#{content.content_count.to_i}回" %>
        </div>
      <% end %>
      <h3 class="descriptions-ranking">意味投稿回数</h3>
      <% @description_post_ranking.each.with_index(1) do |description, i| %>
        <div class="rank">
          第
          <%= i %>
          位
          <%= link_to "#{description.nickname}さん", profile_path(description.id), class: "ranking-nickname" %><%= "#{description.description_count.to_i}回" %>
        </div>
      <% end %>
      <h3 class="sentences-ranking">例文投稿回数</h3>
      <% @sentence_post_ranking.each.with_index(1) do |sentence, i| %>
        <div class="rank">
          第
          <%= i %>
          位
          <%= link_to "#{sentence.nickname}さん", profile_path(sentence.id), class: "ranking-nickname" %><%= "#{sentence.sentence_count.to_i}回" %>
        </div>
      <% end %>
      <h3 class="diaries-ranking">日記投稿回数</h3>
      <% @diary_post_ranking.each.with_index(1) do |diary, i| %>
        <div class="rank">
          第
          <%= i %>
          位
          <%= link_to "#{diary.nickname}さん", profile_path(diary.id), class: "ranking-nickname" %><%= "#{diary.diary_count.to_i}回" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/contents/new.html.erb
<%= render "shared/header" %>

<%= form_with model: @content, url: contents_path, method: :post, local: true do |f| %>

  <div class="new-show-content-main">
    <h1>
      単語を追加
    </h1>

    <div class="error-messages">
      <%= render 'shared/error_messages', model: f.object %>
    </div>

    <div class="font-size-twenty-five">
      <%# 品詞 %>
      <div>
        品詞
        <span class="indispensable">必須</span>
      </div>
      <%= f.collection_select(:part_id, Part.all, :id, :name, {}, {class:"select-box", id:"content-part"}) %>

      <%# 単語 %>
      <div>
        単語
        <span class="indispensable">必須</span>
      </div>
      <div>
        <%= f.text_field :word, class:"word-input", id:"word_id"%>
      </div>

      <div class="caution">
        ※固有名詞の追加は禁止です。
      </div>

      <%# 送信ボタン %>
      <div>
        <%= f.submit "追加する", class:"new-btn" %>
      </div>
    </div>
  </div>

<% end %>

<%= render "shared/footer" %>

app/views/contents/search.html.erb
<%= render 'shared/header'%>

<div class="search-main">

  <h1><%= "'#{params[:keyword]}'の検索結果" %></h1>

  <div class="contents row">
    <% @contents.each do |content| %>
      <%= render partial: "search_result", locals: { contents: content } %>
    <% end %>
  </div>

</div>

<%= render "shared/footer" %>

app/views/contents/show.html.erb
<%= render "shared/header" %>

<div class="ok-flash">
  <% if flash[:notice] %>
    <%= flash[:notice] %>
  <% end %>
</div>

<div class="show-content-main">
  <% if user_signed_in? %>
    <div class="position-right">
      <%= link_to "単語を編集", edit_content_path(@content.id), class: "edit-btn" %>
    </div>
  <% end %>
  <div class="show-content-top">
    <div class="show-content-top-left">
      <div class="word">
        <div class="break-all">
          <%= @content.word %>
        </div>
      </div>

      <div>
        <%= @content.part.name %>
      </div>
    </div>

    <div class="show-content-top-right">
      <h2>
        <%= link_to "#{@content.word}の編集履歴", content_contents_history_path(@content.id), class:"edited-history" %>
      </h2>
      <% @contents_histories.each do |history| %>
        <div>
          <%= link_to "#{history.user.nickname}さん", profile_path(history.user.id), class: "edited-nickname" %>
          <br><%= history.created_at.strftime("%Y-%m-%d %H:%M") %>
        </div>
        <div>
          <%= history.word %>
        </div>
      <% end %>
    </div>
  </div>


  <div class="show-content-bottom">
    <div class="bottom-description">
      <h2>
        意味
        <% if user_signed_in? %>
          <%= link_to "＋", new_content_description_path(@content.id), class: "plus-btn" %>
        <% end %>
      </h2>

      <div class="show-content-description-group">
        <% if @descriptions.present? %>
          <% @descriptions.each do |description| %>
            <div class="show-content-description">
              <div>
                <%= link_to "#{description.user.nickname}さん", profile_path(description.user.id) %>
              </div>
              <div class="break-all">
                <%= simple_format(description.english_text) %>
              </div>
              <% if user_signed_in? && description.user.id == current_user.id %>
                <%= link_to "編集", edit_content_description_path(@content.id, description.id), class: "edit-btn" %>
                <%= link_to "削除", content_description_path(@content.id, description.id), method: :delete, class: "delete-btn" %>
              <% end %>
            </div>
          <% end %>
        <% else %>
          意味のデータが存在しません
        <% end %>
      </div>
    </div>

    <div class="bottom-sentence">
      <h2>
        例文
        <% if user_signed_in? %>
          <%= link_to "＋", new_content_sentence_path(@content.id), class: "plus-btn" %>
        <% end %>
      </h2>

      <% if @sentences.present? %>
        <% @sentences.each do |sentence| %>
          <div class="bottom-one-sentence">
            <div class="bottom-sentence-info">
              <div>
                <%= link_to "#{sentence.user.nickname}", profile_path(sentence.user.id) %>
              </div>
              <div>
                <%= sentence.created_at.strftime("%Y-%m-%d %H:%M") %>
              </div>
            </div>
            <br><b>英語</b>
            <div>
              <%= simple_format(sentence.english_text) %>
            </div>

            <% if sentence.japanese_text.present? %>
              <div>
                <b>日本語</b>
              </div> 
              <div>
                <%= simple_format(sentence.japanese_text) %>
              </div>
            <% end %>

            <% if user_signed_in? && sentence.user.id == current_user.id %>
              <%= link_to "編集", edit_content_sentence_path(@content.id, sentence.id),class: "edit-btn" %>
              <%= link_to "削除", content_sentence_path(@content.id, sentence.id), method: :delete, class: "delete-btn" %>
            <% end %>
          </div>
        <% end %>
      <% else %>
        <div>
          例文のデータが存在しません
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= render "shared/footer" %>