config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    post '/users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  get "contents/about" => "contents#about"

  root to: 'contents#index'

  resources :diaries
  resources :profiles, except: [:index, :destroy]

  resources :contents, except: [:destroy] do
    resources :descriptions, except: [:index, :show]
    resources :sentences, except: [:index, :show]
    resources :contents_histories, only: [:show]
    collection do
      get 'search'
    end
  end
end

app/models/diary.rb
class Diary < ApplicationRecord
  belongs_to :user

  with_options presence: true do
    validates :title, format: { with: /\A[\w\s!?,."'¥$%&]+\z/ }
    validates :text, format: { with: /\A[\w\s!?,."'¥$%&]+\z/ }
  end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :specified_diary, only: [:edit, :update, :destroy]
  before_action :specified_user, only: [:edit, :destroy]

  def index
    @diaries = Diary.order('created_at DESC')
  end

  def show
    @diaries = current_user.diary.order('created_at DESC')
  end

  def new
    @diary = Diary.new
  end

  def create
    @diary = Diary.new(diary_params)
    if @diary.save
      make_count
      redirect_to diary_path(current_user.id),
      notice: '日記の作成に成功しました'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @diary.update(diary_params)
      redirect_to diary_path(current_user.id),
      notice: '日記の編集に成功しました'
    else
      render :edit
    end
  end

  def destroy
    if @diary.destroy
      redirect_to diary_path(current_user.id),
      notice: '日記の削除に成功しました'
    else
      render :show
    end
  end

  private

  def diary_params
    params.require(:diary).permit(:title, :text).merge(user_id: current_user.id)
  end

  def specified_diary
    @diary = Diary.find(params[:id])
  end

  def specified_user
    redirect_to root_path unless @diary.user.id == current_user.id
  end

  def make_count
    sum = current_user.diary_count.to_i + 1
    current_user.update_column(:diary_count, sum)
  end
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/views/diaries/edit.html.erb
<%= render "shared/header"%>

<%= form_with model: @diary, url: diary_path, method: :patch, local: true do |f| %>

  
<div class="position-center">
  <div class="font-size-twenty-five">

    <h2>
      日記
    </h2>

    <div class="error-messages">
      <%= render 'shared/error_messages', model: f.object %>
    </div>

    <div>
      タイトル
    </div>

    <div>
      <%= f.text_field :title, class:"diary_title", placeholder: "English text only（必須）" %>
    </div>

    <div>
      内容
    </div>

    <div>
      <%= f.text_area :text, class:"diary_text", placeholder: "English text only（必須）", cols: 50, rows: 10 %>
    </div>

    <div>
      <%= f.submit "作成する", class:"new-btn" %>
    </div>
  </div>
</div>

<% end %>

<%= render "shared/footer" %>

app/views/diaries/index.html.erb
<%= render "shared/header"%>

<div class="new-edit-diaries-main">

  <h1>
    みんなの日記
  </h1>

  <% if @diaries.exists? %>

    <div class="diaries-group">
    <% @diaries.each do |diary|  %>
      <div class="one-diary">
        <div>
          <%= diary.created_at.strftime("%Y-%m-%d %H:%M")%>
        </div>

        <div class="diary-title">
          <%= diary.title %>
        </div>

        <div class="diary-text">
          <%= diary.text %>
        </div>

        <% if user_signed_in? && current_user.id == diary.user_id %>
          <div>
            <%= link_to "編集", edit_diary_path(diary.id), class: "edit-btn" %>
            <%= link_to "削除", diary_path(diary.id), method: :delete, class: "delete-btn" %>
          </div>
        <% end %>
      </div>
    <% end %>
    </div>

  <% else %>

    表示できる日記がありません。

  <% end %>
</div>

<%= render "shared/footer" %>

app/views/diaries/new.html.erb
<%= render "shared/header"%>

<%= form_with model: @diary, url: diaries_path, method: :post, local: true do |f| %>

  
<div class="position-center">
  <div class="font-size-twenty-five">

    <h2>
      日記
    </h2>

    <div class="error-messages">
      <%= render 'shared/error_messages', model: f.object %>
    </div>

    <div>
      タイトル
    </div>

    <div>
      <%= f.text_field :title, class:"diary_title", placeholder: "English text only（必須）" %>
    </div>

    <div>
      内容
    </div>

    <div>
      <%= f.text_area :text, class:"diary_text", placeholder: "English text only（必須）", cols: 50, rows: 10 %>
    </div>

    <div>
      <%= f.submit "作成する", class:"new-btn" %>
    </div>
  </div>
</div>

<% end %>

<%= render "shared/footer" %>

app/views/diaries/show.html.erb
<%= render "shared/header"%>

  <div class="ok-flash">
    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>
  </div>

<div class="new-edit-diaries-main">

  <h1>
    あなたの日記
    <%= link_to "＋", new_diary_path, class:"plus-btn" %>
  </h1>

  <% if @diaries.exists? %>

    <div class="diaries-group">
    <% @diaries.each do |diary|  %>
      <div class="one-diary">
        <div>
          <%= diary.created_at.strftime("%Y-%m-%d %H:%M")%>
        </div>

        <div class="diary-title">
          <%= diary.title %>
        </div>

        <div class="diary-text">
          <%= diary.text %>
        </div>

        <% if user_signed_in? && current_user.id == diary.user_id %>
          <div>
            <%= link_to "編集", edit_diary_path(diary.id), class: "edit-btn" %>
            <%= link_to "削除", diary_path(diary.id), method: :delete, class: "delete-btn" %>
          </div>
        <% end %>
      </div>
    <% end %>
    </div>

  <% else %>

    表示できる日記がありません。

  <% end %>
</div>

<%= render "shared/footer" %>