config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    post '/users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  get "contents/about" => "contents#about"

  root to: 'contents#index'

  resources :diaries
  resources :profiles, except: [:index, :destroy]

  resources :contents, except: [:destroy] do
    resources :descriptions, except: [:index, :show]
    resources :sentences, except: [:index, :show]
    resources :contents_histories, only: [:show]
    collection do
      get 'search'
    end
  end
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer-contents">
  <div class="about-me">
    About Me
  </div>
  <div class="portfolio">
    <div class="footer-left">
      <ul>
        <li><%= link_to "WyvezのGithub", "https://github.com/Chukoto/wyvez", class: "footer-link" %></li>
        <li><%= link_to "WordSrockのGithub", "https://github.com/Chukoto/wordstock", class: "footer-link" %></li>
      </ul>
    </div>
    <div class="footer-right">
      <ul>
        <li><%= link_to "Github", "https://github.com/chukoto", class: "footer-link" %></li>
        <li><%= link_to "Qiita", "https://qiita.com/NedzumiNeko", class: "footer-link" %></li>
        <li><%= link_to "Twitter", "https://twitter.com/NedzumiNeko", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class='top-header'>
  <div class="header-frame">
    <div class='search-bar-contents'>
      <%= link_to image_tag('wordstock.png', size: "111x72", alt: "ロゴ", class: 'logo'), "/" %>
      <%= form_with(url: search_contents_path , method: :get, class: "search-form", local: true) do |f|%>
        <%= f.text_field :keyword, placeholder: "キーワードから探す", class: "search-input" %>
        <%= f.submit "Search", class: "search-btn" %>
      <% end %>
    </div>
    <div class="nav">
      <ul class="lists-left">
        <li><%= link_to "みんなの日記をみる", diaries_path, class: "diaries-list" %></li>
        <% if user_signed_in? %>
          <li><%= link_to "自分の日記をみる", diary_path(current_user.id), class: "diary-list" %></li>
        <% end %>
      </ul>

      <ul class="lists-right">
        <% if user_signed_in? %>
          <li><%= link_to "#{current_user.nickname}", profile_path(current_user.id) %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "logout" %></li>
        <% else %>
          <li><%= link_to "ゲストログイン（閲覧用）", users_guest_sign_in_path, method: :post, class: "login" %></li>
          <li><%= link_to "ログイン", new_user_session_path, class: "login" %></li>
          <li><%= link_to "新規登録", new_user_registration_path, class: "sign-up" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</header>